# This is a basic workflow to help you get started with Actions

name: Issues to Hexo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened,edited,deleted,closed,reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_USER: VirgilChen97
  GIT_EMAIL: virgilchen97@gmail.com
  HEXO_REPO: VirgilChen97/my-blog-hexo
  HEXO_BRANCH: master
  ISSUE_USERNAME: VirgilChen97
  ISSUE_REPO: notes
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Hexo-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 设置 Hexo repo key
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_REPO_KEY}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: 下载 Hexo 所在 repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HEXO_REPO }}
          ref: ${{ env.HEXO_BRANCH }}
          path: hexo
          submodules: recursive

      - name: 安装 Python
        uses: actions/setup-python@v2.2.2
        
      - name: 安装必要python依赖
        run: pip3 install requests
      
      - name: 安装 Node.js
        uses: actions/setup-node@v2.4.0
        
      - name: 安装 hexo-cli
        run: npm install -g hexo-cli
        
      - name: 导出所有 issue 为 Hexo 文章
        run: python3 issuesToHexo.py ${{env.ISSUE_USERNAME}} ${{env.ISSUE_REPO}} hexo/source/_posts
        
      - name: 设置 Hexo deploy repo key
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_KEY}}
        run: |
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
      
      - name: 发布 Hexo 博客
        run: |
          cd hexo
          npm i
          hexo g
          hexo d
